DichVuThuCungKVH/Areas/Admin/Controllers/TaiKhoansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DichVuThuCungKVH.Model;

namespace DichVuThuCungKVH.Areas.Admin.Controllers
{
    public class TaiKhoansController : Controller
    {
        private DACSEntities db = new DACSEntities();

        // GET: Admin/TaiKhoans
        public ActionResult Index()
        {
            return View(db.TaiKhoans.ToList());
        }

        // Action cho tìm kiếm
        public ActionResult Search(string searchString)
        {
            // Tìm kiếm trong danh sách tài khoản dựa trên chuỗi searchString
            var taiKhoans = db.TaiKhoans.Where(t => t.TenTK.Contains(searchString)).ToList();

            // Trả về view với kết quả tìm kiếm
            return View("Index", taiKhoans);
        }

        // GET: Admin/TaiKhoans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // GET: Admin/TaiKhoans/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/TaiKhoans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTK,TenTK,MatKhau,LoaiTK,TrangThai")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                // Đặt trạng thái mặc định là hoạt động
                taiKhoan.TrangThai = true;
                
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taiKhoan);
        }

        // GET: Admin/TaiKhoans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: Admin/TaiKhoans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTK,TenTK,MatKhau,LoaiTK,TrangThai")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taiKhoan);
        }

        // GET: Admin/TaiKhoans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: Admin/TaiKhoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DichVuThuCungKVH/Areas/Admin/Views/TaiKhoans/Create.cshtml
@model DichVuThuCungKVH.Model.TaiKhoan

@{
    ViewBag.Title = "Tạo Mới Tài Khoản";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Tạo Mới Tài Khoản</h6>
        </div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    
                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.TenTK, "Tên Tài Khoản", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenTK, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.MatKhau, "Mật Khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.MatKhau, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.LoaiTK, "Loại Tài Khoản", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.LoaiTK, 
                                new List<SelectListItem> {
                                    new SelectListItem { Text = "Admin", Value = "Admin" },
                                    new SelectListItem { Text = "Nhân Viên", Value = "NhanVien" },
                                    new SelectListItem { Text = "Khách Hàng", Value = "KhachHang" }
                                }, 
                                "Chọn loại tài khoản", 
                                new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LoaiTK, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.TrangThai, "Trạng Thái", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="custom-control custom-switch">
                                @Html.CheckBoxFor(model => model.TrangThai.Value, new { @class = "custom-control-input", @checked = "checked" })
                                <label class="custom-control-label" for="TrangThai_Value">Hoạt động</label>
                            </div>
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save"></i> Lưu
                            </button>
                            @Html.ActionLink("Quay Lại", "Index", null, new { @class = "btn btn-secondary" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DichVuThuCungKVH/Areas/Admin/Views/TaiKhoans/Delete.cshtml
@model DichVuThuCungKVH.Model.TaiKhoan

@{
    ViewBag.Title = "Xóa Tài Khoản";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-danger">Xóa Tài Khoản</h6>
        </div>
        <div class="card-body">
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i> Bạn có chắc chắn muốn xóa tài khoản này?
            </div>

            <div class="table-responsive">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 200px;">Tên Tài Khoản</th>
                            <td>@Html.DisplayFor(model => model.TenTK)</td>
                        </tr>
                        <tr>
                            <th>Loại Tài Khoản</th>
                            <td>@Html.DisplayFor(model => model.LoaiTK)</td>
                        </tr>
                        <tr>
                            <th>Trạng Thái</th>
                            <td>
                                @if (Model.TrangThai == true)
                                {
                                    <span class="badge bg-success">Hoạt động</span>
                                }
                                else
                                {
                                    <span class="badge bg-danger">Khóa</span>
                                }
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color mt-3">
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash"></i> Xóa
                    </button>
                    @Html.ActionLink("Quay Lại", "Index", null, new { @class = "btn btn-secondary" })
                </div>
            }
        </div>
    </div>
</div>

DichVuThuCungKVH/Areas/Admin/Views/TaiKhoans/Details.cshtml
@model DichVuThuCungKVH.Model.TaiKhoan

@{
    ViewBag.Title = "Chi Tiết Tài Khoản";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container mt-4">
    <div class="card shadow rounded">
        <div class="card-header bg-primary text-white">
            <h3 class="mb-0">Chi Tiết Tài Khoản</h3>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-4">Tên Tài Khoản:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.TenTK)</dd>

                <dt class="col-sm-4">Mật Khẩu:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.MatKhau)</dd>

                <dt class="col-sm-4">Loại Tài Khoản:</dt>
                <dd class="col-sm-8">@Html.DisplayFor(model => model.LoaiTK)</dd>

                <dt class="col-sm-4">Trạng Thái:</dt>
                <dd class="col-sm-8">
                    @if (Model.TrangThai == true)
                    {
                        <span class="badge bg-success">Hoạt động</span>
                    }
                    else
                    {
                        <span class="badge bg-danger">Khóa</span>
                    }
                </dd>
            </dl>
        </div>
        <div class="card-footer text-end">
            @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.MaTK }, new { @class = "btn btn-warning me-2" })
            @Html.ActionLink("Quay lại danh sách", "Index", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>

DichVuThuCungKVH/Areas/Admin/Views/TaiKhoans/Edit.cshtml
@model DichVuThuCungKVH.Model.TaiKhoan

@{
    ViewBag.Title = "Chỉnh Sửa Tài Khoản";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Chỉnh Sửa Tài Khoản</h6>
        </div>
        <div class="card-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.MaTK)

                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.TenTK, "Tên Tài Khoản", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenTK, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenTK, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.MatKhau, "Mật Khẩu", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.PasswordFor(model => model.MatKhau, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.LoaiTK, "Loại Tài Khoản", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.LoaiTK, 
                                new List<SelectListItem> {
                                    new SelectListItem { Text = "Admin", Value = "Admin" },
                                    new SelectListItem { Text = "Nhân Viên", Value = "NhanVien" },
                                    new SelectListItem { Text = "Khách Hàng", Value = "KhachHang" }
                                }, 
                                "Chọn loại tài khoản", 
                                new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.LoaiTK, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row mb-3">
                        @Html.LabelFor(model => model.TrangThai, "Trạng Thái", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="custom-control custom-switch">
                                @Html.CheckBoxFor(model => model.TrangThai.Value, new { @class = "custom-control-input" })
                                <label class="custom-control-label" for="TrangThai_Value">Hoạt động</label>
                            </div>
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-save"></i> Lưu
                            </button>
                            @Html.ActionLink("Quay Lại", "Index", null, new { @class = "btn btn-secondary" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DichVuThuCungKVH/Areas/Admin/Views/TaiKhoans/Index.cshtml
@model IEnumerable<DichVuThuCungKVH.Model.TaiKhoan>

@{
    ViewBag.Title = "Quản Lý Tài Khoản";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Quản Lý Tài Khoản</h6>
            <a href="@Url.Action("Create")" class="btn btn-success">
                <i class="fas fa-user-plus"></i> Thêm Mới
            </a>
        </div>
        <div class="card-body">
            <!-- Form tìm kiếm -->
            @using (Html.BeginForm("Search", "TaiKhoans", FormMethod.Get))
            {
                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="input-group">
                            <input type="text" name="searchString" class="form-control" placeholder="Tìm kiếm tài khoản..." />
                            <button type="submit" class="btn btn-primary">
                                <i class="fas fa-search"></i> Tìm kiếm
                            </button>
                        </div>
                    </div>
                </div>
            }

            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                    <thead class="table-light text-center">
                        <tr>
                            <th>Tên Tài Khoản</th>
                            <th>Mật Khẩu</th>
                            <th>Loại Tài Khoản</th>
                            <th>Trạng Thái</th>
                            <th>Hành Động</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (!Model.Any())
                        {
                            <tr>
                                <td colspan="5" class="text-center text-muted">Không có tài khoản nào được tìm thấy.</td>
                            </tr>
                        }
                        else
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.TenTK)</td>
                                    <td>@Html.DisplayFor(modelItem => item.MatKhau)</td>
                                    <td>@Html.DisplayFor(modelItem => item.LoaiTK)</td>
                                    <td>
                                        @if (item.TrangThai == true)
                                        {
                                            <span class="badge bg-success">Hoạt động</span>
                                        }
                                        else
                                        {
                                            <span class="badge bg-danger">Khóa</span>
                                        }
                                    </td>
                                    <td class="text-center text-nowrap">
                                        <a href="@Url.Action("Edit", new { id = item.MaTK })" class="btn btn-warning btn-sm">
                                            <i class="fas fa-edit"></i> Chỉnh Sửa
                                        </a>
                                        <a href="@Url.Action("Details", new { id = item.MaTK })" class="btn btn-info btn-sm">
                                            <i class="fas fa-info-circle"></i> Chi Tiết
                                        </a>
                                        <a href="@Url.Action("Delete", new { id = item.MaTK })" class="btn btn-danger btn-sm" onclick="return confirm('Bạn có chắc chắn muốn xóa tài khoản này?');">
                                            <i class="fas fa-trash-alt"></i> Xóa
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#dataTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.24/i18n/Vietnamese.json"
                },
                responsive: true
            });
        });
    </script>
}