DichVuThuCungKVH/Areas/Admin/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DichVuThuCungKVH.Model;

namespace DichVuThuCungKVH.Areas.Admin.Controllers
{
    public class NhanViensController : Controller
    {
        private readonly DACSEntities db = new DACSEntities();

        // GET: Admin/NhanViens
        public ActionResult Index()
        {
            var nhanViens = db.NhanViens.Include(n => n.TaiKhoan);
            return View(nhanViens.ToList());
        }

        // GET: Admin/NhanViens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Create
        public ActionResult Create()
        {
            ViewBag.MaTK = new SelectList(db.TaiKhoans, "MaTK", "TenTK");
            return View();
        }

        // POST: Admin/NhanViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,TenNV,ChucVu,ChiNhanh,NgaySinh,SDT,DiaChi,GioiTinh,MaTK,Email")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.NhanViens.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaTK = new SelectList(db.TaiKhoans, "MaTK", "TenTK", nhanVien.MaTK);
            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTK = new SelectList(db.TaiKhoans, "MaTK", "TenTK", nhanVien.MaTK);
            return View(nhanVien);
        }

        // POST: Admin/NhanViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,TenNV,ChucVu,ChiNhanh,NgaySinh,SDT,DiaChi,GioiTinh,MaTK,Email")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaTK = new SelectList(db.TaiKhoans, "MaTK", "TenTK", nhanVien.MaTK);
            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: Admin/NhanViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult DonHangDaDat()
        {

            var danhSachDonHang = db.DonHangs.ToList();
            return View(danhSachDonHang);
        }
        public ActionResult SuaDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }

            return View(donHang);
        }

        [HttpPost]
        public ActionResult SuaDonHang(DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                // Cập nhật thông tin đơn hàng trong cơ sở dữ liệu
                db.Entry(donHang).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("DonHangDaDat");
            }

            return View(donHang);
        }
        public ActionResult XemChiTietDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }

            return View(donHang);
        }
        public ActionResult XoaDonHang(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }

            return View(donHang);
        }

        [HttpPost, ActionName("XoaDonHang")]
        [ValidateAntiForgeryToken]
        public ActionResult XacNhanXoa(int id)
        {
            try
            {
                DonHang donHang = db.DonHangs.Find(id);
                if (donHang == null)
                {
                    return HttpNotFound();
                }

                // Xóa tất cả chi tiết đơn hàng trước
                var chiTietDonHang = db.CTDonHangs.Where(ct => ct.MaDH == id).ToList();
                foreach (var ct in chiTietDonHang)
                {
                    db.CTDonHangs.Remove(ct);
                }

                // Sau đó xóa đơn hàng
                db.DonHangs.Remove(donHang);
                db.SaveChanges();

                TempData["Success"] = "Đã xóa đơn hàng thành công!";
                return RedirectToAction("DonHangDaDat");
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Không thể xóa đơn hàng: " + ex.Message;
                return RedirectToAction("DonHangDaDat");
            }
        }
        public ActionResult DanhSachSuDungDichVu()
        {
            // Lấy danh sách phiếu nhận từ cơ sở dữ liệu
            var danhSachPhieuNhan = db.PhieuNhans.ToList();

            return View(danhSachPhieuNhan);
        }
        public ActionResult ChinhSuaPhieuNhan(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Lấy thông tin phiếu nhận từ cơ sở dữ liệu theo id
            PhieuNhan phieuNhan = db.PhieuNhans.Find(id);

            if (phieuNhan == null)
            {
                return HttpNotFound();
            }

            return View(phieuNhan);
        }

        [HttpPost]
        public ActionResult CapNhatPhieuNhan(PhieuNhan phieuNhan)
        {
            if (ModelState.IsValid)
            {
                // Xử lý cập nhật thông tin phiếu nhận trong cơ sở dữ liệu
                db.Entry(phieuNhan).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("DanhSachSuDungDichVu");
            }

            // Nếu ModelState.IsValid là false, có thể in các lỗi ModelState để xem lý do
            foreach (var modelState in ViewData.ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
            }

            return View(phieuNhan);
        }
        public ActionResult XoaPhieuNhan(int id)
        {
            try
            {
                var phieuNhan = db.PhieuNhans.Find(id);
                if (phieuNhan == null)
                {
                    return Json(new { success = false, message = "Phiếu nhận không tồn tại." });
                }

                db.PhieuNhans.Remove(phieuNhan);
                db.SaveChanges();

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }
    }
}

DichVuThuCungKVH/Areas/Admin/Views/NhanViens/CapNhatPhieuNhan.cshtml
@model DichVuThuCungKVH.Model.PhieuNhan

@{
    ViewBag.Title = "Chỉnh Sửa Phiếu Nhận";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chỉnh Sửa Phiếu Nhận</h2>

@using (Html.BeginForm("CapNhatPhieuNhan", "NhanViens", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thông Tin Phiếu Nhận</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaPhieu)

        <div class="form-group">
            @Html.LabelFor(model => model.MaTC, "Mã Thú Cưng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaTC", null, "-- Chọn Thú Cưng --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaTC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaSDDV, "Mã Lượt Sử Dụng Dịch Vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaSDDV, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.MaSDDV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrangTruocTiepNhan, "Tình Trạng Trước Tiếp Nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (!string.IsNullOrEmpty(Model.TinhTrangTruocTiepNhan))
                {
                    <img src="@Url.Content("~/Images/TinhTrangTruocTiepNhan/" + Model.TinhTrangTruocTiepNhan)" alt="Ảnh Trước Tiếp Nhận" style="max-width: 200px; max-height: 200px;" />
                }
                <input type="file" name="fileTinhTrangTruocTiepNhan" id="fileTinhTrangTruocTiepNhan" onchange="previewImage('fileTinhTrangTruocTiepNhan', 'previewTinhTrangTruocTiepNhan')" />
                <img id="previewTinhTrangTruocTiepNhan" src="#" alt="Ảnh Xem Trước" style="max-width: 200px; max-height: 200px; display: none;" />
                @Html.ValidationMessageFor(model => model.TinhTrangTruocTiepNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrangSauTiepNhan, "Tình Trạng Sau Tiếp Nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (!string.IsNullOrEmpty(Model.TinhTrangSauTiepNhan))
                {
                    <img src="@Url.Content("~/Images/TinhTrangSauTiepNhan/" + Model.TinhTrangSauTiepNhan)" alt="Ảnh Sau Tiếp Nhận" style="max-width: 200px; max-height: 200px;" />
                }
                <input type="file" name="fileTinhTrangSauTiepNhan" id="fileTinhTrangSauTiepNhan" onchange="previewImage('fileTinhTrangSauTiepNhan', 'previewTinhTrangSauTiepNhan')" />
                <img id="previewTinhTrangSauTiepNhan" src="#" alt="Ảnh Xem Trước" style="max-width: 200px; max-height: 200px; display: none;" />
                @Html.ValidationMessageFor(model => model.TinhTrangSauTiepNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NguoiGiao, "Người Giao", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguoiGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NguoiNhan, "Người Nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguoiNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayNhan, "Ngày Nhận", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NgayNhan, "{0:yyyy-MM-dd HH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.NgayNhan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrangDichVu, "Tình Trạng Dịch Vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TinhTrangDichVu, new List<SelectListItem>
                {
                    new SelectListItem { Text = "Đang xử lý", Value = "Đang xử lý" },
                    new SelectListItem { Text = "Hoàn thành", Value = "Hoàn thành" },
                    new SelectListItem { Text = "Hủy", Value = "Hủy" }
                }, "-- Chọn Tình Trạng --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TinhTrangDichVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTra, "Ngày Trả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NgayTra, "{0:yyyy-MM-dd HH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.NgayTra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NguoiTra, "Người Trả", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NguoiTra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NguoiTra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, "Ghi Chú", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<script>
    function previewImage(inputId, imageId) {
        var input = document.getElementById(inputId);
        var image = document.getElementById(imageId);

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                image.src = e.target.result;
                image.style.display = 'block';
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

DichVuThuCungKVH/Areas/Admin/Views/NhanViens/ChinhSuaPhieuNhan.cshtml
@model IEnumerable<DichVuThuCungKVH.Model.PhieuNhan>

@{
    ViewBag.Title = "Danh Sách Sử Dụng Dịch Vụ";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="mt-4 mb-4 text-primary">📋 Danh Sách Sử Dụng Dịch Vụ</h2>

<div style="max-height: 600px; overflow-y: auto;">
    <table class="table table-bordered table-hover table-striped text-center align-middle">
        <thead class="table-dark sticky-top">
            <tr>
                <th>Mã Phiếu Nhận</th>
                <th>Mã Thú Cưng</th>
                <th>Mã Lượt Sử Dụng Dịch Vụ</th>
                <th>Ảnh Trước Tiếp Nhận</th>
                <th>Ảnh Sau Tiếp Nhận</th>
                <th>Người Giao</th>
                <th>Người Nhận</th>
                <th>Ngày Nhận</th>
                <th>Tình Trạng Dịch Vụ</th>
                <th>Ngày Trả</th>
                <th>Người Trả</th>
                <th>Ghi Chú</th>
                <th>Hành Động</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var phieuNhan in Model)
            {
                <tr>
                    <td>@phieuNhan.MaPhieu</td>
                    <td>@phieuNhan.MaTC</td>
                    <td>@phieuNhan.MaSDDV</td>
                    <td>
                        @if (!string.IsNullOrEmpty(phieuNhan.TinhTrangTruocTiepNhan))
                        {
                            <img src="@Url.Content("~/Images/ThuCung/" + phieuNhan.TinhTrangTruocTiepNhan)" 
                                 alt="Ảnh Trước" width="100" height="100" 
                                 style="object-fit: cover; border-radius: 5px;" />
                        }
                        else
                        {
                            <span class="text-muted">Không có ảnh</span>
                        }
                    </td>
                    <td>
                        @if (!string.IsNullOrEmpty(phieuNhan.TinhTrangSauTiepNhan))
                        {
                            <img src="@Url.Content("~/Images/ThuCung/" + phieuNhan.TinhTrangSauTiepNhan)" 
                                 alt="Ảnh Sau" width="100" height="100" 
                                 style="object-fit: cover; border-radius: 5px;" />
                        }
                        else
                        {
                            <span class="text-muted">Không có ảnh</span>
                        }
                    </td>
                    <td>@phieuNhan.NguoiGiao</td>
                    <td>@phieuNhan.NguoiNhan</td>
                    <td>@phieuNhan.NgayNhan?.ToString("dd/MM/yyyy")</td>
                    <td>@phieuNhan.TinhTrangDichVu</td>
                    <td>@phieuNhan.NgayTra?.ToString("dd/MM/yyyy")</td>
                    <td>@phieuNhan.NguoiTra</td>
                    <td>@phieuNhan.GhiChu</td>
                    <td>
                        <a href="@Url.Action("ChinhSuaPhieuNhan", "NhanViens", new { id = phieuNhan.MaPhieu })" 
                           class="btn btn-sm btn-primary mb-1">
                            ✏️ Sửa
                        </a>
                        <a href="@Url.Action("XoaPhieuNhan", "NhanViens", new { id = phieuNhan.MaPhieu })" 
                           class="btn btn-sm btn-danger" 
                           onclick="return confirm('Bạn có chắc chắn muốn xóa phiếu nhận này?');">
                            🗑️ Xóa
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DichVuThuCungKVH/Areas/Admin/Views/NhanViens/DonHangDaDat.cshtml
@model IEnumerable<DichVuThuCungKVH.Model.DonHang>

@{
    ViewBag.Title = "Đơn Hàng Đã Đặt";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Đơn Hàng Đã Đặt</h2>

<table class="table">
    <tr>
        <th>Mã Đơn Hàng</th>
        <th>Ngày Đặt</th>
        <th>Ngày Giao</th>
        <th>Trạng Thái Thanh Toán</th>
        <th>Hành Động</th>
    </tr>

    @foreach (var donHang in Model)
    {
        <tr>
            <td>@donHang.MaDH</td>
            <td>@donHang.NgayDat</td>
            <td>@donHang.NgayGiao</td>
            <td>@(donHang.TrangThaiThanhToan == true ? "Đã thanh toán" : "Chưa thanh toán")</td>
            <td>
                @Html.ActionLink("Sửa đơn hàng", "SuaDonHang", "NhanViens", new { id = donHang.MaDH }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Xem chi tiết đơn hàng", "XemChiTietDonHang", "NhanViens", new { id = donHang.MaDH }, new { @class = "btn btn-primary" })
                <a href="@Url.Action("XoaDonHang", "NhanViens", new { id = donHang.MaDH })" class="btn btn-danger" onclick="return confirm('Bạn có chắc chắn muốn xóa đơn hàng này?');">Xóa</a>
            </td>
        </tr>
    }
</table>

DichVuThuCungKVH/Areas/Admin/Views/NhanViens/SuaDonHang.cshtml
@model DichVuThuCungKVH.Model.DonHang

@{
    ViewBag.Title = "Chỉnh Sửa Đơn Hàng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chỉnh Sửa Đơn Hàng</h2>

@using (Html.BeginForm("SuaDonHang", "NhanViens", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thông Tin Đơn Hàng</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDH)

        <div class="form-group">
            @Html.LabelFor(model => model.NgayDat, "Ngày Đặt", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NgayDat, "{0:yyyy-MM-dd HH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGiao, "Ngày Giao", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.NgayGiao, "{0:yyyy-MM-dd HH:mm:ss}", new { @class = "form-control", @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThaiThanhToan, "Trạng Thái Thanh Toán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TrangThaiThanhToan, new List<SelectListItem>
                {
                    new SelectListItem { Text = "Đã thanh toán", Value = "true" },
                    new SelectListItem { Text = "Chưa thanh toán", Value = "false" }
                }, "-- Chọn Trạng Thái --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TrangThaiThanhToan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

DichVuThuCungKVH/Areas/Admin/Views/NhanViens/XoaDonHang.cshtml
@{
    ViewBag.Title = "XoaDonHang";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@model DichVuThuCungKVH.Model.DonHang

<h2>Xóa Đơn Hàng</h2>

<p>Bạn có chắc muốn xóa đơn hàng này?</p>

@using (Html.BeginForm("XoaDonHang", "NhanViens", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.MaDH)

    <input type="submit" value="Xác nhận" class="btn btn-danger" />
    <a href="@Url.Action("DonHangDaDat", "NhanViens")" class="btn btn-default">Hủy bỏ</a>
}

DichVuThuCungKVH/Areas/Admin/Views/NhanViens/XoaPhieuNhan.cshtml
@model DichVuThuCungKVH.Model.PhieuNhan

@{
    ViewBag.Title = "Xóa Phiếu Nhận";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid px-4">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-danger"><i class="fas fa-trash-alt me-2"></i> Xác Nhận Xóa Phiếu Nhận</h6>
        </div>
        <div class="card-body">
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle me-2"></i> Bạn có chắc chắn muốn xóa phiếu nhận <strong>#@Model.MaPhieu</strong>? Hành động này không thể hoàn tác.
            </div>
            <div class="row mb-3">
                <div class="col-md-6">
                    <p><strong>Mã Thú Cưng:</strong> @(Model.MaTC.HasValue ? Model.MaTC.ToString() : "Không có thông tin")</p>
                    <p><strong>Người Giao:</strong> @(string.IsNullOrEmpty(Model.NguoiGiao) ? "Không có thông tin" : Model.NguoiGiao)</p>
                    <p><strong>Ngày Nhận:</strong> @(Model.NgayNhan.HasValue ? Model.NgayNhan.Value.ToString("dd/MM/yyyy HH:mm") : "Chưa xác định")</p>
                </div>
            </div>
            @using (Html.BeginForm("XoaPhieuNhan", "NhanViens", new { id = Model.MaPhieu }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">
                        <i class="fas fa-trash me-2"></i> Xóa
                    </button>
                    <a href="@Url.Action("PhieuCuaLuotSDDV", new { id = Model.MaSDDV })" class="btn btn-secondary">
                        <i class="fas fa-times me-2"></i> Hủy
                    </a>
                </div>
            }
        </div>
    </div>
</div>