DichVuThuCungKVH/Controllers/DSachThuCungController.cs
using DichVuThuCungKVH.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DichVuThuCungKVH.Controllers
{
    public class DSachThuCungController : Controller
    {
        private DACSEntities db = new DACSEntities();

        // GET: DSThuCung
        public ActionResult KhachHang()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "User");
            }
            var maTaiKhoan = Convert.ToInt32(Session["MaTaiKhoan"].ToString());
            var kh = db.KhachHangs.SingleOrDefault(n => n.MaTK == maTaiKhoan);
            return View(kh);

        }
        public ActionResult DonHang()
        {
            if (Session["TaiKhoan"] == null || Session["TaiKhoan"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "User");
            }
            var maTaiKhoan = Convert.ToInt32(Session["MaTaiKhoan"].ToString());
            var dh = db.CTDonHangs.SingleOrDefault(n => n.MaDH == maTaiKhoan);
            return View(dh);
        }
        public ActionResult DanhSachThuCung()
        {
            if (Session["TaiKhoan"] == null || string.IsNullOrEmpty(Session["TaiKhoan"].ToString()))
            {
                return RedirectToAction("DangNhap", "User");
            }

            var maTaiKhoanObject = Session["MaTaiKhoan"];
            if (maTaiKhoanObject != null && int.TryParse(maTaiKhoanObject.ToString(), out var maTaiKhoan))
            {
                var khachHang = db.KhachHangs.SingleOrDefault(n => n.MaTK == maTaiKhoan);

                if (khachHang != null)
                {
                    var maKhachHang = khachHang.MaKH;

                    var danhSachThuCung = db.ThuCungs.Where(n => n.MaKH == maKhachHang).ToList();

                    ViewBag.MaKhachHang = maKhachHang;

                    ViewBag.DanhSachThuCung = danhSachThuCung;

                    return View();
                }
                else
                {
                    return RedirectToAction("ThongBaoKhongTimThayKhachHang", "User");
                }
            }
            else
            {
                return RedirectToAction("DangNhap", "User");
            }
        }

    }
}

DichVuThuCungKVH/Controllers/DVTCController.cs
using DichVuThuCungKVH.Model;
using System.Linq;
using System.Web.Mvc;

namespace DichVuThuCung.Controllers
{
    public class DVTCController : Controller
    {
        private DACSEntities db = new DACSEntities();

        // GET: DVTC
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DichVu()
        {
            return View();
        }

        public ActionResult CacDichVu()
        {
            return PartialView();
        }

        public ActionResult SanPhamPartial()
        {
            var listSanPham = (from cd in db.SanPhams select cd ).ToList();
            return PartialView(listSanPham);
        }

        public ActionResult NavPartial()
        {
            return PartialView();
        }

        public ActionResult Slider()
        {
            return View();
        }
        public ActionResult ChiTietSanPham(int id)
        {
            var sanpham = from sp in db.SanPhams
                          where sp.MaSP == id
                          select sp;
            return View(sanpham.Single());
        }
        public ActionResult FormDatLich()
        {
            return View();
        }
        public ActionResult LoginLogoutPartial()
        {
            return PartialView();
        }
        public ActionResult LoginLogout()
        {
            return PartialView("LoginLogoutPartial");
        }
    }
}

DichVuThuCungKVH/Controllers/DichVuController.cs
using DichVuThuCungKVH.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DichVuThuCungKVH.Controllers
{
    public class DichVuController : Controller
    {
        private DACSEntities db = new DACSEntities();

        // GET: DichVu
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DVTrongGiu()
        {
            ViewBag.MaDV = new SelectList(db.DichVus.ToList().OrderBy(n => n.TenDichVu), "MaDV", "TenDV");
            return View();
        }

        [HttpPost]
        public ActionResult DvTrongGiu(FormCollection collection, KhachHang kh, CTPhieuNhan_DichVu ct)
        {
            ViewBag.MaDV = new SelectList(db.DichVus.ToList().OrderBy(n => n.TenDichVu), "MaDV", "TenDV");

            // ViewBag.ThongBao = "Không được để trống";
            ViewBag.TenKH = collection["sTenKH"];
            ViewBag.SDT = collection["sSDT"];
            ViewBag.Email = collection["sEmail"];
            ViewBag.MaDV = new SelectList(db.DichVus.ToList().OrderBy(n => n.TenDichVu), "MaDV", "TenDV", int.Parse(collection["MaDV"]));

            //      var sHoTen = collection["HoTen"];
            //    var sDienThoai = collection["DienThoai"];
            //  var sEmail = collection["Email"];
            //var sYeuCau = db.DichVus.ToList();
            //var selectList = new SelectList(sYeuCau, "MaDV", "TenDV");
            //ViewBag.MaDV = selectList;
            //var sYeuCau = collection["YeuCau"];
            //     var selectList = new SelectList(db.DichVus.ToList().OrderBy(n => n.TenDichVu), "MaDV", "TenDV");
            // ViewBag.YeuCau = selectList;
            //ViewBag.MaDV = new SelectList(db.DichVus.ToList().OrderBy(n => n.TenDichVu), "MaDV", "TenDV", int.Parse(collection["MaDV"]));
            /*       if (String.IsNullOrEmpty(sHoTen))
                   {
                       ViewData["err1"] = "Họ tên không được rỗng";
                   }
                   else if (String.IsNullOrEmpty(sDienThoai))
                   {
                       ViewData["err2"] = "Điện thoại không được rỗng";
                   }
                   else if (String.IsNullOrEmpty(sEmail))
                   {
                       ViewData["err3"] = "Email không được rỗng";
                   }
                   else if (String.IsNullOrEmpty(s))
                   {
                    ViewData["err4"] = "Yêu cầu không được rỗng";
                   }
                   else
                   {
                       KhachHang kh = new KhachHang
                       {
                           TenKH = sHoTen,
                           SDT = sDienThoai,
                           Email = sEmail,
                       };
                       CTPhieuNhan_DichVu ct = new CTPhieuNhan_DichVu
                       {
                          DichVuSuDung = ,
                       };
            */
            kh.TenKH = collection["sTenKH"];
            kh.SDT = collection["sDienThoai"];
            kh.Email = collection["sEmail"];
            ct.DichVuSuDung = (collection["TenDV"]);
            // ViewBag.MaDV = new SelectList(db.DichVus.ToList().OrderBy(n => n.TenDichVu), "MaDV", "TenDV", int.Parse(collection["MaDV"]));
            db.KhachHangs.Add(kh);
            db.CTPhieuNhan_DichVu.Add(ct);
            db.SaveChanges();
            return RedirectToAction("DVTrongGiu");

            // return View();
        }

        [HttpGet]
        public ActionResult DangKyDichVu()
        {
            // Populate dropdowns or perform any other necessary setup here
            return PartialView();
        }

        [HttpPost]
        public ActionResult DangKyDichVu(KhachHang khachHang)
        {
            // Validate and save the registration data to the database
            khachHang.TinhTrangLienHe = false;
            if (ModelState.IsValid)
            {
                // Save to the database
                var existingTaiKhoan = db.TaiKhoans.FirstOrDefault(tk => tk.Email == khachHang.Email);

                if (existingTaiKhoan != null)
                {
                    // If a matching TaiKhoan is found, link it to the KhachHang
                    khachHang.MaTK = existingTaiKhoan.MaTK;
                }
                khachHang.ThoiGianDangKy = DateTime.Now;
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();

                // Redirect to a success page or another action
                return RedirectToAction("DichVu","DVTC");
            }

            // If validation fails, return to the registration form with errors
            return View(khachHang);
        }
    }
}

DichVuThuCungKVH/Controllers/UserController.cs
using DichVuThuCungKVH.Model;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DichVuThuCungKVH.Controllers
{
    public class UserController : Controller
    {
        private DACSEntities db = new DACSEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(FormCollection collection)
        {
            var sHoTen = collection["HoTen"];
            var sTenTK = collection["TenDN"];
            var sMatKhau = collection["MatKhau"];
            var sMatKhauNhapLai = collection["MatKhauNL"];
            var sDiaChi = collection["DiaChi"];
            var sEmail = collection["Email"];
            var sDienThoai = collection["DienThoai"];
            var dNgaySinh = String.Format("{0:MM/dd/yyyy}", collection["NgaySinh"]);

            if (String.IsNullOrEmpty(sHoTen))
            {
                ViewData["err1"] = "Họ tên không được rỗng";
            }
            else if (String.IsNullOrEmpty(sTenTK))
            {
                ViewData["err2"] = "Tên đăng nhập không được rỗng";
            }
            else if (String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["err3"] = "Mật khẩu không được rỗng";
            }
            else if (String.IsNullOrEmpty(sMatKhauNhapLai))
            {
                ViewData["err4"] = "Nhập lại mật khẩu không được rỗng";
            }
            else if (sMatKhau != sMatKhauNhapLai)
            {
                ViewData["err4"] = "Mật khẩu nhập lại không khớp";
            }
            else if (String.IsNullOrEmpty(sDiaChi))
            {
                ViewData["err5"] = "Địa chỉ không được rỗng";
            }
            else if (String.IsNullOrEmpty(sEmail))
            {
                ViewData["err6"] = "Email không được rỗng";
            }
            else if (db.TaiKhoans.Any(n => n.TenTK == sTenTK))
            {
                ViewBag.ThongBao = "Tên đăng nhập đã tồn tại";
            }
            else if (db.KhachHangs.Any(n => n.Email == sEmail))
            {
                ViewBag.ThongBao = "Email đã được sử dụng";
            }
            else
            {
                KhachHang kh = new KhachHang
                {
                    TenKH = sHoTen,
                    Email = sEmail,
                    DiaChi = sDiaChi,
                    SDT = sDienThoai,
                    NgaySinh = DateTime.Parse(dNgaySinh)
                };

                TaiKhoan tk = new TaiKhoan
                {
                    TenTK = sTenTK,
                    MatKhau = sMatKhau
                };

                db.KhachHangs.Add(kh);
                db.TaiKhoans.Add(tk);
                db.SaveChanges();
                return RedirectToAction("DangNhap");
            }
            return View();
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection collection)
        {


            var sTenDN = collection["TenDN"];
            var sMatKhau = collection["Matkhau"];
            if (String.IsNullOrEmpty(sTenDN))
            {
                ViewData["Err1"] = "Bạn chưa nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(sMatKhau))
            {
                ViewData["Err2"] = "Phải nhập mật khẩu";
            }
            else
            {

                TaiKhoan tk = db.TaiKhoans.SingleOrDefault(n => n.TenTK == sTenDN && n.MatKhau == sMatKhau);
                if (tk != null)
                {
                    ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                    Session["TaiKhoan"] = tk;
                    Session["MaTaiKhoan"] = tk.MaTK;
                    return RedirectToAction("Index", "DVTC");
                }

                else
                {
                    ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }

            }
            return View();


        }
    }
}

DichVuThuCungKVH/Views/DVTC/CacDichVu.cshtml
<div class=tabProduct>
    <div class=row>
        <div class="homepage-row-product-title text-center">
            <h1>
                <a href="" title="">Cửa hàng Dịch Vụ Thú Cưng KVH</a>

            </h1>

        </div>
        <div class="homepage-row-product-title-1 text-center">

            <h2>
                <a href="/dich-vu-cham-soc-thu-cung" title="Các gói dịch vụ chăm sóc thú cưng">Xem thêm gói dịch vụ chăm sóc thú cưng</a>
                <hr class="underline-title">
            </h2>
        </div>
    </div>
    <div>
        <div class="hidden-xs">
            <div class="row">
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Dịch vụ trông giữ chó mèo">
                        <figure class="img-wrap square">
                            <img src="https://zoipet.com/wp-content/uploads/2023/07/bang-gia-khach-san-cho-meo-thu-cung-pet-hotel.jpg" alt="Dịch vụ trông giữ chó mèo">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Dịch vụ trông giữ chó mèo</h3>
                            </div>
                        </div>
                    </a>

                </div>
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Chăm sóc thú cưng">
                        <figure class="img-wrap square">
                            <img src="https://static.chotot.com/storage/chotot-kinhnghiem/c2c/2019/11/nghe-cham-soc-thu-cung-1.jpg" alt="Chăm sóc thú cưng">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Chăm sóc thú cưng</h3>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Cứu hộ thú cung">
                        <figure class="img-wrap square">
                            <img src="https://www.petmom.vn/uploads/contents/1590765042_53238e0e3389cd205b8b.jpg" alt="Cứu hộ thú cung">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Cứu hộ thú cung</h3>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Khách sạn chó mèo">
                        <figure class="img-wrap square">
                            <img src="https://kinpetshop.com/wp-content/uploads/khach-san-cho-meo-tphcm.jpg" alt="Khách sạn chó mèo">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Khách sạn chó mèo</h3>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Spa cho thú cưng là gì?">
                        <figure class="img-wrap square">
                            <img src="https://dogstar.vn/wp-content/uploads/2022/08/nhan-vien-cham-soc-khach-san-thu-cung-la-gi-can-luu-y-gi-1.png" alt="Spa cho thú cưng là gì?">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Spa cho thú cưng là gì?</h3>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Dịch vụ tắm cho chó mèo">
                        <figure class="img-wrap square">
                            <img src="https://mcdn.coolmate.me/uploads/November2021/spa-thu-cung-la-gi-20.jpg" alt="Dịch vụ tắm cho chó mèo">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Dịch vụ tắm cho chó mèo</h3>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Dịch vụ cắt tỉa lông chó mèo">
                        <figure class="img-wrap square">
                            <img src="https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2020/1/19/779656/46523460_21313917568.jpg" alt="Dịch vụ cắt tỉa lông chó mèo">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Dịch vụ cắt tỉa lông chó mèo</h3>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-xs-6">
                    <a href="#id1" class="hover14" title="Thời trang thú cưng">
                        <figure class="img-wrap square">
                            <img src="https://image.phunuonline.com.vn/fckeditor/upload/2020/20200305/images/thoi-trang-may-mac-cho-cho-phat-_1583419103.jpg" alt="Thời trang thú cưng">
                        </figure>
                        <div class="caption">
                            <div class="caption-text">
                                <h3>Thời trang thú cưng</h3>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>


    </div>
</div>

DichVuThuCungKVH/Views/DVTC/ChiTietSanPham.cshtml
<h2 class="text-center">CHI TIẾT SẢN PHẨM</h2>
<hr>

<div class="thumbnail" style=" border: 1px solid #ddd; padding: 15px; border-radius: 5px; background-color: #f9f9f9;">
    <div class="text-center">
        <h4 class="tensp" style=" color: #333; font-size: 20px; margin-top: 10px;">
            @Model.TenSP
        </h4>
    </div>

    <img src="~/Images/SanPham/@Model.Anh" alt="@Model.TenSP" />
    <br>
    <br>
    <div class="mota" style=" margin-top: 15px;">
        <p style=" text-indent: 20px;line-height: 1.6; font-size: 18px;">
            @Html.Raw(Model.MoTaSP.ToString().Replace("\n", "</p><p>&nbsp&nbsp&nbsp&nbsp&nbsp"))
        </p>
    </div>
    <div class="text-right">
        <p style="font-size: 18px; color: #e44d26;font-weight: bold; margin-top: 15px;" class="giaban">Giá bán: <span>@Html.FormatValue(@Model.GiaBan, "{0:#,##0}") VNĐ</span></p>
        <p style="font-size:20px; font-weight:bold;">
            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = @Model.MaSP, url = Request.Url.ToString() })"; data-id="@Model.MaSP">
                Chọn mua
            </a>
        </p>
    </div>
</div>

DichVuThuCungKVH/Views/DVTC/FormDatLich.cshtml
@{
    ViewBag.Title = "FormDatLich";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>FormDatLich</h2>

DichVuThuCungKVH/Views/DVTC/LoginLogoutPartial.cshtml
@using DichVuThuCungKVH.Model
@{
    TaiKhoan tk = (TaiKhoan)Session["TaiKhoan"];
}

@if (Session["TaiKhoan"] == null)//login
{
    <li> <a href="~/User/DangKy"><span class="glyphicon glyphicon-user"></span>Đăng ký</a></li>
    <li>
        <a href="@Url.Action("DangNhap","User", new { url = Request.Url.ToString() })">
            <span class="glyphicon glyphicon-log-in"></span> Đăng nhập
        </a>
    </li>
}
else // logout
{
    <li> <a href="#"><span class="glyphicon glyphicon-user"></span>Xin chào:@tk.TenTK</a></li>
    <li> <a href="@Url.Action("DangXuat","User")"><span class="glyphicon glyphicon-log-out"></span>Đăng xuất </a></li>
}

DichVuThuCungKVH/Views/DVTC/NavPartial.cshtml
    <div class="container_menu">

    <div class="navone">

        <p class="lbl">DANH MỤC SẢN PHẨM <i class="fa fa-caret-down text-25"></i></p>

        <ul class="ul primary">
            <li class="not-pro"><a href="/"><span class="span-root">Trang chủ</span></a></li>
            <li class="is-pro">
                <a href="#">
                    <span class="span-root">Shop thú cưng</span>
                </a>
                <div class="level2">
                    <div class="box-sub-nav  clear ">
                        <a href="#id1" class="cat1" title="Dịch Vụ">
                            Danh Sách Các Dịch Vụ
                        </a>


                    </div>

                    <div class="box-sub-nav  clear ">
                        <a href="#id2" class="cat1" title="Sản Phẩm">
                            Danh Sách Các Sản Phẩm
                        </a>


                    </div>
                </div>
            </li>


            <li class="is-pro">
                <a href="@Url.Action("DichVu","DVTC")">
                    <span class="span-root">Dịch vụ thú cưng</span>
                </a>
                <div class="level2">
                    <div class="box-sub-nav  clear ">
                        <a href="#" class="cat1" title="Chăm sóc thú cưng">
                            Chăm sóc thú cưng
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="#" class="cat1" title="Khách sạn chó mèo">
                            Khách sạn chó mèo
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="#" class="cat1" title="Dịch vụ tắm cho chó mèo">
                            Dịch vụ tắm cho chó mèo
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="#" class="cat1" title="Dịch vụ trông giữ chó mèo">
                            Dịch vụ trông giữ chó mèo
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="#" class="cat1" title="Spa cho thú cưng là gì?">
                            Spa cho thú cưng là gì?
                        </a>
                    </div>
                    <div class="box-sub-nav  clear ">
                        <a href="#" class="cat1" title="Dịch vụ cắt tỉa lông chó mèo">
                            Dịch vụ cắt tỉa lông chó mèo
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="#" class="cat1" title="Cứu hộ thú cung">
                            Cứu hộ thú cung
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="#" class="cat1" title="Thời trang thú cưng">
                            Thời trang thú cưng
                        </a>
                    </div>
                </div>
            </li>

            <li class="is-pro">
                <a href="#">
                    <span class="span-root">Tài Khoản</span>
                </a>
                <div class="level2">
                    <div class="box-sub-nav  clear ">
                        <a href="@Url.Action("DangNhap","User")" class="cat1" title="Đăng nhập ">
                            Đăng Nhập
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="@Url.Action("DangKy","User")" class="cat1" title="Đăng Ký">
                            Đăng Ký
                        </a>
                    </div>
                </div>
            </li>
            <li class="is-pro">
                <a href="#">
                    <span class="span-root">Người Dùng</span>
                </a>
                <div class="level2">
                    <div class="box-sub-nav clear">
                        <a href="@Url.Action("DanhSachThuCung","DSachThuCung")" class="cat1" title="ds thú cưng ">
                            Danh Sách Thú Cưng
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="@Url.Action("DonHang","DSachThuCung")" class="cat1" title="Đơn hàng">
                            Đơn Hàng
                        </a>
                    </div>
                    <div class="box-sub-nav ">
                        <a href="@Url.Action("KhachHang","DSachThuCung")" class="cat1" title="Thông tin ">
                            Thông Tin Khách Hàng
                        </a>
                    </div>
                </div>
            </li>
            <li class="is-pro">
                <a href="@Url.Action("Login", "Home", new { area = "Admin" })">
                    <span class="span-root">Admin</span>
                </a>
            </li>
        </ul>
    </div><!--//-->

    <div class="clear"></div>
</div>

DichVuThuCungKVH/Views/DVTC/SanPhamPartial.cshtml
@model List<DichVuThuCungKVH.Model.SanPham>
<div class=row>
    <section class="col-md-12 md-section">
        <div class="row ">
            <section class="homepage-row-product">
                <div class="row">
                    <div class="homepage-row-product-title text-center">
                        <h2>
                            <a href="" title="Shop">Sản Phẩm Thú Cưng</a>
                            <hr class="underline-title">
                        </h2>
                    </div>
                </div>
                @foreach (var sanPham in Model)
                {
                    <div class="col-md-3">
                        <div class="product-block text-center">
                            <a href="#" title="@sanPham.TenSP">
                                <div class="img-wrap">
                                    <img src="~/Images/SanPham/@sanPham.Anh" alt="@sanPham.TenSP">
                                </div>
                                <h3 style="min-height:10px;">
                                    <a href="@Url.Action("ChiTietSanPham","DVTC", new { id = sanPham.MaSP })" class="text-decoration-none">@sanPham.TenSP</a>
                                </h3>
                                <h4 class="product-price">
                                    <div class="price">@sanPham.GiaBan</div>
                                </h4>
                            </a>
                            <a href="@Url.Action("ThemGioHang","GioHang", new { ms = sanPham.MaSP, url = Request.Url.ToString() })" class="btn btn-danger btn-custom-product-add" onclick="add_to_cart(this);" data-id="@sanPham.MaSP" >
                                Chọn mua
                            </a>
                        </div>
                    </div>
                }
        </div>
    </section>
</div>
<style>
    .btn-custom-product-add {
        background-color: #3498db; /* Màu nền của nút */
        color: #fff; /* Màu chữ của nút */
        padding: 8px 15px;
        border: none;
        border-radius: 3px;
        cursor: pointer;
        text-decoration: none;
        transition: background-color 0.3s ease;
    }

        .btn-custom-product-add:hover {
            background-color: #2980b9; /* Màu nền của nút khi di chuột vào */
        }
</style>

DichVuThuCungKVH/Views/DVTC/Slider.cshtml
<div class="swiper-container swiper-main-container">
    <div class=swiper-wrapper>
        <a class="swiper-slide" href="#" title="Dịch vụ cắt tỉa lông chó mèo" target="_blank">
            <img src="~/Images/Slider/petspa.jpg" alt="Dịch vụ cắt tỉa lông chó mèo" style="width: 100%;">
        </a>
        <a class="swiper-slide" href="#" title="Shop thú cưng" target="_blank">                <img src="~/Images/Slider/petshop.jpg" alt="Shop thú cưng" style="width: 100%;">                </a>
        <a class="swiper-slide" href="#" title="Khách sạn cho chó" target="_blank">                <img src="~/Images/Slider/pethotel.jpg" alt="Khách sạn cho chó" style="width: 100%;">                </a>
    </div>
    <div class=swiper-pagination></div>
</div>

DichVuThuCungKVH/Views/DVTC/index.cshtml
    
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_TrangchuLayoutPage.cshtml";
}